#!/bin/sh
perl bandstats.pl "Rolling Stones"
perl bandstats.pl "Led Zeppelin"
perl bandstats.pl "Beatles"
perl bandstats.pl "Pink Floyd"
perl bandstats.pl "Yes"
perl bandstats.pl "Who"
perl bandstats.pl "Van Halen"
perl bandstats.pl "Queen"
perl bandstats.pl "Journey"
perl bandstats.pl "Cars"
perl bandstats.pl "Foreigner"
perl bandstats.pl "Boston"
perl bandstats.pl "Supertramp"
perl bandstats.pl "Elton John"
perl bandstats.pl "Electric Light Orchestra"
perl bandstats.pl "Creedence Clearwater Revival"
perl bandstats.pl "David Bowie"
perl bandstats.pl "Bruce Springsteen"
perl bandstats.pl "Doors"
perl bandstats.pl "Rush"
perl bandstats.pl "Billy Joel"
perl bandstats.pl "Tom Petty And The Heartbreakers"
perl bandstats.pl "Steve Miller Band"
perl bandstats.pl "Bad Company"
perl bandstats.pl "Lynyrd Skynyrd"
perl bandstats.pl "Eagles"
perl bandstats.pl "Styx"
perl bandstats.pl "Eric Clapton"
perl bandstats.pl "Paul Mccartney And Wings"
perl bandstats.pl "Fleetwood Mac"
perl bandstats.pl "Van Morrison"
perl bandstats.pl "Genesis"
perl bandstats.pl "Zz Top"
perl bandstats.pl "Rod Stewart"
perl bandstats.pl "George Thorogood"
perl bandstats.pl "Aerosmith"
perl bandstats.pl "Blue Oyster Cult"
perl bandstats.pl "Warren Zevon"
perl bandstats.pl "J. Geils Band"
perl bandstats.pl "War"
perl bandstats.pl "Joe Walsh"
perl bandstats.pl "Meatloaf"
